/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-test-fixtures")
    id("spring-common-conventions")

    kotlin("kapt")
}

dependencies {
    testFixturesImplementation(libs.testcontainers)
    testFixturesImplementation(libs.testcontainers.mysql)
    testFixturesImplementation(libs.testcontainers.jdbc)

    testFixturesImplementation(libs.bundles.modules.test.db)
    testFixturesImplementation(libs.spring.data.querydsl.jpa) {
        artifact {
            classifier = "jakarta"
        }
    }

    kaptTestFixtures(libs.spring.data.querydsl.apt) {
        artifact {
            classifier = "jakarta"
        }
    }

    testFixturesImplementation(libs.bundles.test.kotest)
}